In [1]:
import dgl
import torch as th

# 生成 0->1 0->2 0->3 1->3的边
u, v = th.tensor([0, 0, 0, 1]), th.tensor([1, 2, 3, 3])
g = dgl.graph((u, v))

C:\Users\18438\AppData\Local\Continuum\anaconda3\envs\dgl\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\18438\AppData\Local\Continuum\anaconda3\envs\dgl\lib\site-packages\numpy\.libs\libopenblas.EL2C6PLE4ZYW3ECEVIV3OXXGRN2NRFM2.gfortran-win_amd64.dll
C:\Users\18438\AppData\Local\Continuum\anaconda3\envs\dgl\lib\site-packages\numpy\.libs\libopenblas.GK7GX5KEQ4F6UYO3P26ULGBQYHGQO7J4.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"
Using backend: pytorch


In [2]:
g

Graph(num_nodes=4, num_edges=4,
      ndata_schemes={}
      edata_schemes={})

In [4]:
g.nodes()

tensor([0, 1, 2, 3])

In [5]:
g.edges()

(tensor([0, 0, 0, 1]), tensor([1, 2, 3, 3]))

In [6]:
# 获取边的对应端点和边ID
g.edges(form='all')

(tensor([0, 0, 0, 1]), tensor([1, 2, 3, 3]), tensor([0, 1, 2, 3]))

In [7]:
# 如果具有最大ID的节点没有边，在创建图的时候，用户需要明确地指明节点的数量。
g = dgl.graph((u, v), num_nodes=8)

In [8]:
g.nodes()

tensor([0, 1, 2, 3, 4, 5, 6, 7])

In [9]:
g.edges()

(tensor([0, 0, 0, 1]), tensor([1, 2, 3, 3]))

In [10]:
# 对于无向图，需要为每条边都创建两个方向的边
bg = dgl.to_bidirected(g)
bg.edges()

(tensor([0, 0, 0, 1, 1, 2, 3, 3]), tensor([1, 2, 3, 0, 3, 0, 0, 1]))

In [11]:
bg.nodes()

tensor([0, 1, 2, 3, 4, 5, 6, 7])

DGL支持使用 32 位或 64 位的整数作为节点ID和边ID。  
节点和边ID的数据类型必须一致。如果使用 64 位整数， DGL可以处理最多 2的63次方−1 个节点或边。  
不过，如果图里的节点或者边的数量小于 2的63次方−1 ，用户最好使用 32 位整数。  
这样不仅能提升速度，还能减少内存的使用。DGL提供了进行数据类型转换的方法，如下例所示。

In [12]:
edges = th.tensor([2, 5, 3]), th.tensor([3, 5, 0])  # 边：2->3, 5->5, 3->0
g64 = dgl.graph(edges)  # DGL默认使用int64
print(g64.idtype)

torch.int64


In [13]:
g32 = dgl.graph(edges, idtype=th.int32)  # 使用int32构建图
g32.idtype

torch.int32

In [14]:
g64_2 = g32.long()  # 转换成int64
g64_2.idtype

torch.int64

In [15]:
g32_2 = g64.int()  # 转换成int32
g32_2.idtype

torch.int32