In [6]:
import dgl 
import torch as th

g = dgl.graph(([0, 0, 1, 5], [1, 2, 2, 0]))

In [7]:
g.nodes() #为啥默认会生成到5这个最大节点 包括了 3 4

tensor([0, 1, 2, 3, 4, 5])

In [8]:
g.edges()

(tensor([0, 0, 1, 5]), tensor([1, 2, 2, 0]))

In [9]:
g.num_nodes() # 节点数量

6

In [11]:
th.ones(6, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [12]:
# 长度为3的节点特征
g.ndata['x'] = th.ones(g.num_nodes(), 3)

In [13]:
g.ndata

{'x': tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])}

In [14]:
th.ones(6, dtype=th.int32)

tensor([1, 1, 1, 1, 1, 1], dtype=torch.int32)

In [15]:
# 标量整型特征
g.edata['x'] = th.ones(g.num_edges(), dtype=th.int32)

In [16]:
g

Graph(num_nodes=6, num_edges=4,
      ndata_schemes={'x': Scheme(shape=(3,), dtype=torch.float32)}
      edata_schemes={'x': Scheme(shape=(), dtype=torch.int32)})

In [17]:
# 不同名称的特征可以具有不同形状
g.ndata['y'] = th.randn(g.num_nodes(), 5)

In [20]:
# 获取节点1的x特征
g.ndata['x'][1]

tensor([1., 1., 1.])

In [22]:
# 获取边 0-3 的x特征
g.edata['x'][th.tensor([0, 3])]

tensor([1, 1], dtype=torch.int32)

对于加权图，可以通过给边添加权重特征来完成权重的赋值

In [25]:
g.edges()

(tensor([0, 0, 1, 5]), tensor([1, 2, 2, 0]))

In [27]:
weights = th.tensor([0.1, 0.2, 0.5, 0.8])

In [28]:
g.edata['w'] = weights

In [29]:
g

Graph(num_nodes=6, num_edges=4,
      ndata_schemes={'x': Scheme(shape=(3,), dtype=torch.float32), 'y': Scheme(shape=(5,), dtype=torch.float32)}
      edata_schemes={'x': Scheme(shape=(), dtype=torch.int32), 'w': Scheme(shape=(), dtype=torch.float32)})